
name: Stage the app

on:
  pull_request:
    types: [labeled ]
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    
    if: contains(github.event.pull_request.labels.*.name, 'stage')
