# This is a basic workflow to help you get started with Actions

name: Azure Deployment

# Controls when the workflow will run
on:
 
  pull_request:
    branches: [label]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      
